name: Front tests

on:
    push:
        paths:
            - "app/**"
jobs:
    run-app:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./app
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9
                  run_install: false

            - name: Install Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dep
              run: pnpm install

            - name: Install Playwright Browsers
              run: pnpm playwright install --with-deps

            - name: Run tests
              run: pnpm playwright test

            - name: Try to build
              run: pnpm build

    deploy:
        needs: run-app
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master'
        steps:
            - name: Deploy to production
              run: |
                  curl \
                  --request GET '${{ secrets.DEPLOY_HOOK_APP }}' \
                  --header 'Authorization: Bearer ${{ secrets.DEPLOY_HOOK_SECRET }}'
